#!/bin/bash

#============
# Docker
#============

# mysql client
if [ -f /Applications/MySQLWorkbench.app/Contents/MacOS ]; then
	export PATH="${PATH}:/Applications/MySQLWorkbench.app/Contents/MacOS"
fi

export VAGRANT_DEFAULT_PROVIDER=vmware_fusion

# hack for osx agent change in Sierra
{ eval `ssh-agent`; ssh-add -K; } &>/dev/null

# docker
if [ -f /usr/local/bin/docker-machine ]; then
	echo ">>> Setting docker machine to vmdev"
	eval "$(docker-machine env vmdev)"


	VM=vmdev
	DOCKER_MACHINE=/usr/local/bin/docker-machine

	VBOXMANAGE=/Applications/VirtualBox.app/Contents/MacOS/VBoxManage

	BLUE='\033[0;34m'
	GREEN='\033[0;32m'
	NC='\033[0m'

	unset DYLD_LIBRARY_PATH
	unset LD_LIBRARY_PATH

	VM_STATUS=$($DOCKER_MACHINE status $VM 2>&1)
	if [ "$VM_STATUS" != "Running" ]; then
		$DOCKER_MACHINE start $VM
		yes | $DOCKER_MACHINE regenerate-certs $VM
	fi

	eval $($DOCKER_MACHINE env --shell=bash $VM)
fi
